cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: ############ urs access key (generate through IAM user)
      secret-key: ############ urs secret key #########
    end-point:
      uri: ##########provide urs queue url###########
